
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE loan;
TRUNCATE TABLE book_author;
TRUNCATE TABLE book;
TRUNCATE TABLE users;
TRUNCATE TABLE publisher;
TRUNCATE TABLE author;
SET FOREIGN_KEY_CHECKS = 1;


